### ISSUE TITLE
the mobile version issue

### ISSUE THREAD

**Issue by yassineuuu** [yassineuuu/int-gration-Web-Brief#1]
- [x] Page version mobile

- [x] menu humberger

- [x] background de l'image

**Comment by yassineuuu** [comment]
- [ ] Page version mobile

**Comment by yassineuuu** [comment]
la page version mobile est prés tous ce qu'il me reste c'est le menu humberger

**Comment by youssefbm** [comment]
N'oubliez pas le BEM

**Comment by yassineuuu** [comment]
d'accord, merci
