### ISSUE TITLE
the desktop version issue

### ISSUE THREAD

**Issue by yassineuuu** [yassineuuu/int-gration-Web-Brief#2]
- [ ] Page version desktop

**Comment by yassineuuu** [comment]
discord test

**Comment by youssefbm** [comment]
des checklistes sont requises

**Comment by yassineuuu** [comment]
merci pour le rappel

**Comment by yassineuuu** [comment]
version desktop est finis
maintenant  je vais attacké les Breakpoint

**Comment by youssefbm** [comment]
Nice Yacineuuu :)

**Comment by yassineuuu** [comment]
merci youssefbm ;)
