### ISSUE TITLE
Optimisation du code

### ISSUE THREAD

**Issue by yassineuuu** [yassineuuu/int-gration-Web-Brief#4]
- [ ] optimiser le BEM

- [ ] comprésser le code Css

**Comment by youssefbm** [comment]
J'ai remarqué que vous maîtrisez pas encore le build process. Je t'invite à revoir cette partie.

**Comment by youssefbm** [comment]
Hello Yacine, vous n'avez pas respecté la partie CSS. Il faut pas rassembler le code CSS en un seul fichier.

**Comment by yassineuuu** [comment]
j'ai essayer  de faire la concatenation avec deux fichiers scss un qui contient les mixins et un autre  qui contient les variables mais je n'arrive pas à avoir un bon résultats même si j'ai changer le lien liée avec le HTML

**Comment by yassineuuu** [comment]
Est que vous avez des suggéstions concernant ce qu'il faut faire,
merci d'avance.

**Comment by yassineuuu** [comment]
c'est bon j'ai réussie de régler le problem
